name: Build and Publish Android Pre-Release APKs

on:
  schedule:
    # 每天的18:00 UTC，即北京时间次日2:00
    - cron: '0 18 * * *'

permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 设置Java编译环境
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: 编译安卓
        run: |
          sh ./.github/workflows/build.sh canary
          # 检查编译是否成功
          if [ $? -eq 0 ]; then
            git tag "CanaryBuild-${tagVersionName}"
            git push origin "CanaryBuild-${tagVersionName}"
          else
            echo "编译失败，退出..."
            exit 1
          fi
      - name: 上传 APK 到 artifact
        uses: actions/upload-artifact@v3
        with:
          name: temp-apk
          path: ${{github.workspace}}/release/
      - name: 打包脚本
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            ${{github.workspace}}/tagVersionName.txt
            ${{github.workspace}}/versionCode.txt
            ${{github.workspace}}/.github/workflows/upload.py
            ${{github.workspace}}/.github/workflows/configuration.json
            ${{github.workspace}}/.github/workflows/changelog.sh

  sign:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: 下载 APK
        uses: actions/download-artifact@v3
        with:
          name: temp-apk
          path: release/
      - uses: ilharp/sign-android-release@v1
        name: 签名
        id: sign_app
        with:
          releaseDir: release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 34.0.0
      - name: 上传 APK 到 artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-app-apk
          path: ${{steps.sign_app.outputs.signedFile}}



  log:
    needs: sign
    runs-on: ubuntu-latest
    steps:
      - name: 下载脚本
        uses: actions/download-artifact@v3
        with:
          name: package
          path: package/
      - name: 生成构建日志
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
          configuration: "package/.github/workflows/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Changelog to Summary
        run: |
          sh package/.github/changelog.sh Canary
      - name: Upload Changelog as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: changelog.txt

  upload-apk:
    needs: log
    runs-on: ubuntu-latest
    steps:
      - name: 下载签名后的 APK
        uses: actions/download-artifact@v3
        with:
          name: signed-app-apk
          path: release/
      - name: 下载脚本
        uses: actions/download-artifact@v3
        with:
          name: package
          path: package/
      - name: 下载日志
        uses: actions/download-artifact@v3
        with:
          name: Changelog
          path: log/
      - name: 上传 APK
        run: pip install requests markdown && python package/.github/workflows/upload.py
        env:
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
          ALIST_TOKEN: ${{ secrets.ALIST_TOKEN }}
          FORUMS_API_KEY: ${{ secrets.FORUMS_API_KEY }}
          CHANNEL_ID: Canary

